services:
  spark:
    image: apache/spark:3.5.0
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data/delta:/data/delta
      - ./app:/app
    env_file:
      - .env

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    ports:
      - "8888:8888"
    volumes:
      - ./data/delta:/data/delta
      - ./notebooks:/home/jovyan/work
      - ./app:/home/jovyan/app
    env_file:
      - .env
    depends_on:
      - spark

  md-python:
    container_name: md-python
    entrypoint: ["tail", "-f", "/dev/null"]
    build: .
    env_file:
      - .env
    volumes:
      - ./data/delta:/data/delta
      - ./app:/app
