SELECT 
age,
  awards,
  donator_status,
  enemies,
  faction_id,
  forum_posts,
  friends,
  gender,
  honor_id,
  `id`,
  image,
  karma,
  last_action.status AS LastActionStatus,
  last_action.timestamp AS LastActionTimestamp,
  from_unixtime(last_action.timestamp) AS LastActionTimestampClean,
  last_action.relative AS LastActionRelative,
  level,
  life.current AS LifeCurrent,
  life.maximum AS LifeMaximum,
  `name`,
  rank,
  revivable,
  role,
  signed_up,
  from_unixtime(signed_up) AS SignedUpTimestamp,
  spouse.id AS SpouseID,
  spouse.name AS SpouseName,
  spouse.status AS SpouseStatus,
  spouse.days_married AS SpouseDaysMarried
 FROM {{source('torn_user', 'base')}}