SELECT
    name                            AS game_name,
    race,
    galaxy_difficulty               AS difficulty,
    game_pacing,
    research_rate,
    number_of_sectors,
    galaxy_size,
    civilization_proximity,
    habitable_planets,
    extreme_planets,
    version,
    opponents,
    victory_conditions,
    turns,
    result                          AS victory_condition,
    score,
    time_played,
    'galciv4_supernova'             AS game
FROM {{ delta_source('gameanalysis/galciv4_supernova') }}
